/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#0054ba',
        'on-background': '#e2e2e8',
        'on-surface': '#e2e2e8',
        'outline': '#849396',
        'inverse-surface': '#e2e2e8',
        'on-surface-variant': '#bac9cc',
        'error': '#ffb4ab',
        'surface-container-highest': '#333539',
        'surface-variant': '#333539',
        'tertiary': '#f2e9ff',
        'outline-variant': '#3b494c',
        'surface': '#111318',
        'primary': '#e7ecff',
        'on-tertiary-container': '#6c00f7',
        'on-secondary-fixed': '#291a00',
        'surface-container-lowest': '#0c0e12',
        'surface-container': '#1e2024',
        'on-error-container': '#ffdad6',
        'background': '#111318',
        'inverse-on-surface': '#2f3035',
        'tertiary-fixed': '#e9ddff',
        'surface-container-high': '#282a2e',
        'tertiary-fixed-dim': '#d1bcff',
        'secondary-fixed': '#ffe0a0',
        'on-primary-fixed': '#001a43',
        'on-secondary-fixed-variant': '#5c4000',
        'on-tertiary': '#3c0090',
        'on-secondary-container': '#7a5500',
        'on-error': '#690005',
        'primary-fixed-dim': '#aec6ff',
        'on-tertiary-fixed-variant': '#5700c9',
        'primary-container': '#bed0ff',
        'secondary-fixed-dim': '#f0b429',
        'secondary': '#fff3d6',
        'surface-bright': '#37393e',
        'surface-container-low': '#1a1c20',
        'surface-tint': '#aec6ff',
        'on-primary': '#002e6b',
        'primary-fixed': '#d8e2ff',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#004397',
        'surface-dim': '#111318',
        'tertiary-container': '#d9c8ff',
        'secondary-container': '#ffc942',
        'on-secondary': '#3d2800',
        'inverse-primary': '#0059c5',
        'on-tertiary-fixed': '#23005b',
      },
      fontFamily: {
        headline: ['"DM Sans"', 'system-ui', 'sans-serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
        reading: ['Lora', '"Noto Serif SC"', '"Noto Serif JP"', 'Georgia', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
