/** @type {import('tailwindcss').Config} */

/** Helper: reference a CSS variable with Tailwind alpha support */
const c = (name) => `rgb(var(--color-${name}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container':       c('on-primary-container'),
        'on-background':              c('on-background'),
        'on-surface':                 c('on-surface'),
        'outline':                    c('outline'),
        'inverse-surface':            c('inverse-surface'),
        'on-surface-variant':         c('on-surface-variant'),
        'error':                      c('error'),
        'surface-container-highest':  c('surface-container-highest'),
        'surface-variant':            c('surface-variant'),
        'tertiary':                   c('tertiary'),
        'outline-variant':            c('outline-variant'),
        'surface':                    c('surface'),
        'primary':                    c('primary'),
        'on-tertiary-container':      c('on-tertiary-container'),
        'on-secondary-fixed':         c('on-secondary-fixed'),
        'surface-container-lowest':   c('surface-container-lowest'),
        'surface-container':          c('surface-container'),
        'on-error-container':         c('on-error-container'),
        'background':                 c('background'),
        'inverse-on-surface':         c('inverse-on-surface'),
        'tertiary-fixed':             c('tertiary-fixed'),
        'surface-container-high':     c('surface-container-high'),
        'tertiary-fixed-dim':         c('tertiary-fixed-dim'),
        'secondary-fixed':            c('secondary-fixed'),
        'on-primary-fixed':           c('on-primary-fixed'),
        'on-secondary-fixed-variant': c('on-secondary-fixed-variant'),
        'on-tertiary':                c('on-tertiary'),
        'on-secondary-container':     c('on-secondary-container'),
        'on-error':                   c('on-error'),
        'primary-fixed-dim':          c('primary-fixed-dim'),
        'on-tertiary-fixed-variant':  c('on-tertiary-fixed-variant'),
        'primary-container':          c('primary-container'),
        'secondary-fixed-dim':        c('secondary-fixed-dim'),
        'secondary':                  c('secondary'),
        'surface-bright':             c('surface-bright'),
        'surface-container-low':      c('surface-container-low'),
        'surface-tint':               c('surface-tint'),
        'on-primary':                 c('on-primary'),
        'primary-fixed':              c('primary-fixed'),
        'error-container':            c('error-container'),
        'on-primary-fixed-variant':   c('on-primary-fixed-variant'),
        'surface-dim':                c('surface-dim'),
        'tertiary-container':         c('tertiary-container'),
        'secondary-container':        c('secondary-container'),
        'on-secondary':               c('on-secondary'),
        'inverse-primary':            c('inverse-primary'),
        'on-tertiary-fixed':          c('on-tertiary-fixed'),
      },
      fontFamily: {
        headline: ['"DM Sans"', 'system-ui', 'sans-serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
        reading: ['Lora', '"Noto Serif SC"', '"Noto Serif JP"', 'Georgia', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
